# Use the latest Node.js LTS version as the base image
FROM node:lts

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY ./frontend/package.json ./frontend/pnpm-lock.yaml ./

# Install PNPM globally
RUN npm install -g pnpm

# Install project dependencies using PNPM
RUN pnpm install

# Copy the rest of the project files to the working directory
COPY ./frontend .

# Build the Next.js application
CMD [ "pnpm", "dev" ]

# Expose the default Next.js port
EXPOSE 3000
