services:
  api:
    image: avatars-api
    stdin_open: true
    build:
      context: .
      dockerfile: ./backend/dockerfile
    ports:
      - '8080:8080'
    develop:
      watch:
        - path: api
          action: rebuild

  web:
    image: avatars-web
    stdin_open: true
    build:
      context: .
      dockerfile: ./frontend/dockerfile
    ports:
      - '3000:3000'
    develop:
      watch:
        - path: frontend/
          target: /app
          action: sync
