# Use the official Go image as the base image
FROM golang:latest

# Set the working directory inside the container
WORKDIR /app

# Copy the Go module files
COPY ./backend/go.mod  ./

# Download and install the Go dependencies
RUN go mod download

# Copy the source code into the container
COPY ./backend .
# RUN go build -o app
RUN go build -o app .

# Set the port to expose
EXPOSE 8080

# Set the entry point for the container
ENTRYPOINT ["./app"]